# Generated by Django 3.1.7 on 2021-03-28 16:07

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('hot', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=224)),
                ('title', models.CharField(default=True, max_length=150)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Engine_size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='First_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_registration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gearbox', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Old_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550)),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='*')),
                ('body', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('author', models.CharField(blank=True, default='Admin', max_length=50)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('vehicle_description', ckeditor.fields.RichTextField(blank=True)),
                ('vehicle_extras', ckeditor.fields.RichTextField()),
                ('colors', models.CharField(choices=[('white', 'WHITE'), ('black', 'BLACK'), ('blue', 'BLUE'), ('green', 'GREEN'), ('yellow', 'YELLOW'), ('red', 'RED')], default=True, max_length=50)),
                ('selled', models.BooleanField()),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='car.categories')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('poster', models.ImageField(default='static/user.jpg', upload_to='users/poster')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product_images/')),
                ('product', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='car.product')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='contact_detail',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='car.profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_size',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='car.engine_size'),
        ),
        migrations.AddField(
            model_name='product',
            name='first_registration',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='car.first_registration'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='car.fuel'),
        ),
        migrations.AddField(
            model_name='product',
            name='gearbox',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='car.gearbox'),
        ),
        migrations.AddField(
            model_name='product',
            name='mileage',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='car.mileage'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car_model'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='car.name'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='car.old_price'),
        ),
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='car.power'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='car.price'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('message', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.comment', verbose_name='parent')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='car.post')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
